import Header from '@/components/Header';
import Head from 'next/head';
import { requests } from './api/requests';
import { axiosInstance } from './api/axios';
import Banner from '@/components/Banner';
import MovieGallery from '@/components/MovieGallery';

export interface Movie {
  title: string;
  backdrop_path: string;
  media_type?: string;
  release_date?: string;
  first_air_date: string;
  genre_ids: number[];
  id: number;
  name: string;
  origin_country: string[];
  original_language: string;
  original_name: string;
  overview: string;
  popularity: number;
  poster_path: string;
  vote_average: number;
  vote_count: number;
}

interface Movies {
  nowPlaying: Movie[];
  trending: Movie[];
  topRated: Movie[];
  romance: Movie[];
  horror: Movie[];
  comedy: Movie[];
  documentaries: Movie[];
  action: Movie[];
}

export default function Home({
  nowPlaying,
  trending,
  topRated,
  romance,
  horror,
  documentaries,
  comedy,
  action,
}: Movies) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-black'>
        <Header />
        <Banner nowPlaying={nowPlaying} />
        <section className='p-8 space-y-10'>
          <MovieGallery title='Trending' movies={trending} />
          <MovieGallery title='Top Rated' movies={topRated} />
          <MovieGallery title='Romance' movies={romance} />
          <MovieGallery title='Horror' movies={horror} />
          <MovieGallery title='Documentary' movies={documentaries} />
          <MovieGallery title='Comedy' movies={comedy} />
          <MovieGallery title='Action' movies={action} />
        </section>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const [
    nowPlaying,
    trending,
    topRated,
    romance,
    horror,
    documentaries,
    comedy,
    action,
  ] = await Promise.all([
    axiosInstance.get(requests.nowPlaying).then((res) => res.data),
    axiosInstance.get(requests.Trending).then((res) => res.data),
    axiosInstance.get(requests['Top Rated']).then((res) => res.data),
    axiosInstance.get(requests.Romance).then((res) => res.data),
    axiosInstance.get(requests.Horror).then((res) => res.data),
    axiosInstance.get(requests.Documentary).then((res) => res.data),
    axiosInstance.get(requests.Comedy).then((res) => res.data),
    axiosInstance.get(requests.Action).then((res) => res.data),
  ]);

  return {
    props: {
      nowPlaying: nowPlaying.results,
      trending: trending.results,
      topRated: topRated.results,
      romance: romance.results,
      horror: horror.results,
      documentaries: documentaries.results,
      comedy: comedy.results,
      action: action.results,
    },
  };
}
